name: SCANOSS SBOM SCANNER RONAN

on:
  pull_request:
  push:
    branches:
      - '*'

permissions:
  contents: read
  pull-requests: write
  checks: write
  actions: read

jobs:
  scan-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run scan
        run: |
          npm install
          npm run scan

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v3
        with:
          name: SBOM
          path: sbom.spdx.json
