name: SCANOSS SBOM SCANNER

on:
  push:
    branches:
      - '*'

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Docker Registry
        if: env.DOCKER_AUTH_REQUIRED == 'true'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Generate SBOM using SCANOSS Docker
        run: |
          docker pull ghcr.io/scanoss/scanoss-py:v1.19.0
          docker run --rm -v $(pwd):/scanoss ghcr.io/scanoss/scanoss-py:v1.19.0 scan ./ -i sbom.json -o /scanoss/results.json

      - name: Upload SBOM as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: scanoss-results
          path: ./results.json

  generate-charts:
    runs-on: ubuntu-latest
    needs: generate-sbom

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download SBOM Result
        uses: actions/download-artifact@v3
        with:
          name: scanoss-results
          path: ./  # Download to root

      - name: Debug Files
        run: ls -la  # Check if results.json exists

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib pandas

      - name: Generate Charts
        run: |
          mkdir -p charts
          python scripts/generate_charts.py
