name: SCANOSS SBOM SCANNER

on:
  push:
    branches:
      - '*'

jobs:
  generate-sbom-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Docker Registry
        if: env.DOCKER_AUTH_REQUIRED == 'true'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull SCANOSS Docker Image
        run: docker pull ghcr.io/scanoss/scanoss-py:v1.19.0

      - name: Generate SBOM and Create PURLs JSON
        run: |
          # Create output directory and generate SBOM
          mkdir -p sbom_output
          docker run --rm -v $(pwd):/scanoss ghcr.io/scanoss/scanoss-py:v1.19.0 scan ./ --key txnUfW0xwF0KI1U1RW5sDSBL -o ./sbom_output/results.json
          
          echo "Extracting PURLs from SBOM to create a single batch JSON file..."
          jq '{purls: [.components[]?.purl // empty | {purl: .}]}' *.json > ./purls.json
          echo "PURLs JSON file created with $(jq '.purls | length' ./purls.json) PURLs."
          echo "Scanning all PURLs in batch using scanoss-py..."
          docker run --rm -v $(pwd):/scanoss ghcr.io/scanoss/scanoss-py:v1.19.0 comp vu --input ./purls.json --key txnUfW0xwF0KI1U1RW5sDSBL
          echo "Batch scan completed."

      - name: Upload SBOM and PURLs JSON as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scanoss-results
          path: ./sbom_output/results.json

      - name: Upload PURLs JSON as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: purls-json
          path: ./purls.json
